# Configurations
title:            기록의 최전선
longtitle:        Saehim's log
author:           Saehim
email:            saeilee.vxv@gmail.com
description: >
  갓태어난 개발자의 공부 기록.
  앎의 기록에서 멈추는 것이 아니라, 삶의 기록까지 나가길 바라며.

version:          1.0
gitbook_version:  3.2.3

url:              'https://new-pow.github.io/'
baseurl:          ''
rss:              RSS

toc:
  enabled: true
  h_min: 1
  h_max: 3

# markdown render engine.
markdown:         kramdown
kramdown:
  auto_ids:               true
  input:                  GFM
  math_engine:            mathjax
  smart_quotes:           lsquo,rsquo,ldquo,rdquo
  toc_levels:             1..6
  syntax_highlighter:     rouge
  syntax_highlighter_opts:
    guess_lang:           true

syntax_highlighter_style: colorful

markdown_ext:     markdown,mkdown,mkdn,mkd,md

# Permalinks
permalink:        /:categories/:year-:month-:day-:title:output_ext

exclude:
  - _drafts

collections:
  pages:
    output: true
    permalink: /:collection/:path/

page_width: 800px

destination:      ./_site
incremental:      false
regenerate:       true

plugins:
  - jekyll-feed
  - jemoji
